---
- name: Add Github host key
  become: yes
  become_user: jenkins
  lineinfile:
    dest: "{{ jenkins_user_home }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Clone Git repo
  become: yes
  become_user: jenkins
  git:
    dest: "{{ repo_dir }}"
    repo: "{{ git_repo }}"
    force: yes
    version: "{{ branch }}"

- name: Copy Jenkins config files
  become: yes
  become_user: jenkins
  copy:
    src: files/
    dest: "{{ repo_dir }}/docker/jenkins/bootstrap"

- name: Process Jenkins templates
  become: yes
  become_user: jenkins
  shell: "{{ repo_dir }}/docker/jenkins/build.sh"

- name: Jenkins init config
  become: yes
  become_user: jenkins
  shell: "{{ repo_dir }}/docker/jenkins/init.sh"
