- name: Create jenkins group
  group:
    name: jenkins
    gid: 1000
    state: present

- name: Create jenkins user
  user:
    name: jenkins
    uid: 1000
    group: jenkins
    home: "{{ jenkins_user_home }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    state: present

