version: '3.1'

services:
  nginx:
    image: nginx:1.12
    container_name: nginx-proxy
    networks:
      - ci-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "30"

  dockergen:
    image: jwilder/docker-gen:0.7.3
    container_name: nginx-proxy-gen
    networks:
      - ci-net
    depends_on:
      - nginx
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "30"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.5
    container_name: nginx-proxy-le
    networks:
      - ci-net
    depends_on:
      - nginx
      - dockergen
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "30"

volumes:
  conf:
  vhost:
  html:
  certs:

networks:
  ci-net:
    external: true

