---
- name: Enable UFW
  ufw:
    state: enabled

- name: Allow all outgoing
  ufw:
    policy: allow
    direction: outgoing

- name: Deny all incoming
  ufw:
    policy: deny
    direction: incoming

- name: Allow TCP ports 22, 80, 443
  ufw:
    policy: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 22
    - 80
    - 443

- name: Reload UFW
  ufw:
    state: reloaded
