---
- hosts: jenkins
  remote_user: root
  gather_facts: False

  vars_prompt:
    - name: ci_ip
      prompt: "Enter IP address of Jenkins host"

  tasks:
    - name: Set IP as fact
      set_fact:
        jenkins_ip: "{{ ci_ip }}"
    - name: Install Python
      raw: "apt-get update && apt-get -y -q install python"

- hosts: jenkins

  remote_user: root
  gather_facts: True

  roles:
    - role: basic_stuff
      tags:
        - basic

    - role: firewall
      tags:
        - firewall

    - role: jenkins_user
      tags:
        - user

    - role: angstwad.docker_ubuntu
      docker_group_members:
        - jenkins
      tags:
        - docker

    - role: docker_config
      tags:
        - config

    - role: docker_service
      tags:
        - service
