---
- hosts: jenkins
  remote_user: root
  gather_facts: False

  vars_prompt:
    - name: jenkins_ip
      prompt: "Enter IP address of Jenkins host"

  tasks:
    - name: Set IP as fact
      set_fact:
        jenkins_ip: "{{ jenkins_ip }}"
    - name: Install Python
      raw: "apt-get update && apt-get -y -q install python"

- hosts: jenkins

  remote_user: root
  gather_facts: True

  roles:
    - role: basic_stuff
      tags:
        - basic
    - role: firewall
      tags:
        - firewall
    - role: jenkins_user
      tags:
        - user
    - role: angstwad.docker_ubuntu
      tags:
        - docker
      docker_group_members:
        - jenkins
    - role: docker_jenkins
      tags:
        - jenkins
    - role: jenkins_bootstrap_config
      tags:
        - config
