---
- name: Create Docker network
  docker_network:
    name: ci-net
    state: present

- name: Run SonarQube service
  become: yes
  become_user: jenkins
  include: docker.yml
  vars:
    directory: "{{ repo_dir }}/docker/{{ item }}"
  with_items:
    - jenkins
    - nginx

- name: Remove unencrypted config files
  become: yes
  become_user: jenkins
  shell: "find {{ repo_dir }}/docker/jenkins/data/bootstrap/ -not -name bootstrap -delete"
